version: '3.7'
services:
  node:
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - './:/app'
    environment:
      - MODE=DEV
    depends_on:
        - 'db'
        - 'redis'
  db:
    image: postgres:11
    container_name: pg-container
    restart: always
    networks:
      - api-net
    ports:
      - '5432:5432'
    expose: 
      - '5432'
    env_file: .env
  redis:
    image: redis:5
    container_name: redis-container
    volumes:
        - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    expose: 
        - '6379'
    networks: 
        - api-net